### ISSUE TITLE
Plotting data from another executable

### ISSUE THREAD

**Issue by IoannisDadiotis** [AngelJA/ros-qcustomplot#1]
Hi, 
I am trying to use this sample package in order to plot data generated from another executable I have (following similar structure with your 3 files `mainwindow.h`, `mainwindow.cpp`, `main.cpp`). However it is not clear how this can be achieved easily since the examples provided are plotting data for the `MainWindow` class, which inherits from `QMainWindow` and has specific properties.

How can I generalize the use of your package for plotting data generated in another executable (thus from another class I define and instantiate that has nothing to do with `MainWindow`)? Do you have any example of such a use that you would be happy to share with me?
Thanks

**Comment by AngelJA** [comment]
Hi there,

Sorry, I haven't touched this since 2018 and was very surprised to see a post here.

I posted this template publicly, but anything I made with it would have been for my old job. So, unfortunately I don't have any samples to share.

**Comment by IoannisDadiotis** [comment]
Thanks for the immediate response.
